web/router.ex
defmodule Mdiary.Router do
  use Mdiary.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end
  pipeline :browser_session do
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.LoadResource
  end
  pipeline :api do
    plug :accepts, ["json"]
    plug Guardian.Plug.VerifyHeader
    plug Guardian.Plug.LoadResource
  end

  scope "/", Mdiary do
    pipe_through [:browser, :browser_session] # Use the default browser stack

    get "/", PageController, :index
    get "/login", SessionController, :new, as: :login
    post "/login", SessionController, :create, as: :login
    delete "/logout", SessionController, :delete, as: :logout
    get "/logout", SessionController, :delete, as: :logout

    resources "/users", UserController
  end

  scope "/api/v1", Mdiary.Api.V1 do
    pipe_through :api
    resources "/users", UserController, except: [:new, :edit]
    resources "/devices", DeviceController, except: [:new, :edit]
    resources "/migraines", MigraineController, except: [:new, :edit]
  end

  # Other scopes may use custom stacks.
  # scope "/api", Mdiary do
  #   pipe_through :api
  # end
end

web/controllers/session_controller.ex
defmodule Mdiary.SessionController do
  use Mdiary.Web, :controller
  alias Mdiary.User
  alias Mdiary.UserQuery

  def new(conn, params) do
    changeset = User.login_changeset(%User{})
    render(conn, Mdiary.SessionView, "new.html", changeset: changeset)
  end

  def create(conn, params = %{}) do
    user = Repo.one(UserQuery.by_email(params["user"]["email"] || ""))
    if user do
      changeset = User.login_changeset(user, params["user"])
      if changeset.valid? do
        conn
          |> put_flash(:info, "Logged in.")
          |> Guardian.Plug.sign_in(user, :token)
          |> redirect(to: user_path(conn, :index))
        else
          render(conn, "new.html", changeset: changeset)
      end
    else
      changeset = User.login_changeset(%User{})
        |> Ecto.Changeset.add_error(:login, "not found")
      render(conn, "new.html", changeset: changeset)
    end
  end

  def delete(conn, _params) do
    Guardian.Plug.sign_out(conn)
      |> put_flash(:info, "Logged out successfully.")
      |> redirect(to: "/")
  end
end

web/views/session_view.ex
defmodule Mdiary.SessionView do
  use Mdiary.Web, :view

  def render("new.json", assigns) do
    Pison.encode!(assigns.users)
  end
end

web/templates/session/new.html.eex
<%= form_for @changeset, login_path(@conn, :create), [method: :post], fn f -> %>
  <h2 class="form-signin-heading">Please sign in</h2>
  <%= if f.errors != [] do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below:</p>
      <ul>
        <%= for {attr, message} <- f.errors do %>
          <li><%= humanize(attr) %> <%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <label for="email" class="sr-only">Email</label>
    <%= email_input f, :email, class: "form-control" %>
  </div>

  <div class="form-group">
    <label for="password" class="sr-only">Password</label>
    <%= password_input :user, :password, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= submit "Login", class: "btn btn-lg btn-primary btn-block" %>
    <%= link("Sign up",
      to: user_path(@conn, :new),
      class: "btn btn-success pull-right"
    ) %>
  </div>
<% end %>

web/templates/session/unauthenticated.html.eex
<h1>You are unauthenticated!</h1>